### ISSUE TITLE
Select has side-effect that makes it display incorrectly 

### ISSUE THREAD

**Issue by QAFabianHuch** [aforemny/material-components-web-elm#94] opened 2020-03-19 18:04 UTC
As mentioned in  #81, I've noticed some weird side-effect behaviour in Menus, but wasn't able to track them down further (or even coherently explain when they would occur). I've now found a similar issue that I can describe:
# Issue
In a view that first renders an empty select, then (e.g. when a request returns) renders a select with options, the label of the select floats in the middle of the select, overlaying its value. 

## Example
MWE to try out: https://ellie-app.com/8mCdTBPmjxta1

```elm
...

view : State -> Html msg
view state =
    case state.status of
        Fetching ->
            outlinedSelect
                { selectConfig | label = "Index"}
                []

        Elems elems ->
            outlinedSelect
                { selectConfig
                    | label = "Index"
                    , value = Just <| state.selected
                }
                (List.map
                    (\e -> selectOption { selectOptionConfig | value = e } [ Html.text e ])
                    elems
                )
```

This behaviour does __not__ occur when the empty select isn't rendered previously, e.g. by
```elm
...
    case state.status of
        Fetching ->
            text "loading ..."
...
```

# Affected Version(s)
2.11

**Comment by aforemny** [comment] 2020-07-06 08:39
Updated example: https://ellie-app.com/9kWSnmSn87ta1

**Comment by aforemny** [comment] 2020-09-13 12:42
Hi @QAFabianHuch, thank you for raising this issue. This bug relied on the fact that select elements could have zero items which has changed since then. So I think this is not applicable anymore. At least the updated example does not reproduce the original issue anymore. So I am closing this.

If this issue persists, please open another issue for the current version of this library. Thanks!

**Closed by aforemny** 2020-09-13 12:42 UTC
Labels: bug
